package com.gmq.psp.projects.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-03-02T02:27:22.747+01:00
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "http://www.example.org/manageSchoolWSDL/", name = "manageSchoolWSDL")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ManageSchoolWSDL {

    @WebMethod(operationName = "RegisterSubject", action = "http://www.example.org/manageSchoolWSDL/RegisterSubject")
    @WebResult(name = "SubjectResponse", targetNamespace = "http://www.example.org/manageSchoolWSDL/", partName = "recievedSubject")
    public SubjectResponse registerSubject(

        @WebParam(partName = "sentSubject", name = "SubjectRequest", targetNamespace = "http://www.example.org/manageSchoolWSDL/")
        SubjectRequest sentSubject
    );

    @WebMethod(operationName = "RegisterStudent", action = "http://www.example.org/manageSchoolWSDL/RegisterStudent")
    @WebResult(name = "StudentResponse", targetNamespace = "http://www.example.org/manageSchoolWSDL/", partName = "recievedStudent")
    public StudentResponse registerStudent(

        @WebParam(partName = "sentStudent", name = "StudentRequest", targetNamespace = "http://www.example.org/manageSchoolWSDL/")
        StudentRequest sentStudent
    );

    @WebMethod(operationName = "StartAssessment", action = "http://www.example.org/manageSchoolWSDL/StartAssessment")
    @WebResult(name = "AssessmentResponse", targetNamespace = "http://www.example.org/manageSchoolWSDL/", partName = "recievedAssessment")
    public AssessmentResponse startAssessment(

        @WebParam(partName = "sentAssessment", name = "AssessmentRequest", targetNamespace = "http://www.example.org/manageSchoolWSDL/")
        AssessmentRequest sentAssessment
    );
}
