
package com.gmq.psp.projects.soap;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-03-02T02:48:12.314+01:00
 * Generated source version: 3.3.5
 *
 */

public class ManageSchoolWSDL_ManageSchoolWSDLSOAP_Server{

    protected ManageSchoolWSDL_ManageSchoolWSDLSOAP_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ManageSchoolWSDLSOAPImpl();
        String address = "http://localhost:8080/manageSchool/services/manageSchoolWSDLSOAP";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new ManageSchoolWSDL_ManageSchoolWSDLSOAP_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
