
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.gmq.psp.projects.soap;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-03-02T02:27:22.704+01:00
 * Generated source version: 3.3.5
 *
 */

@javax.jws.WebService(
                      serviceName = "manageSchoolWSDL",
                      portName = "manageSchoolWSDLSOAP",
                      targetNamespace = "http://www.example.org/manageSchoolWSDL/",
                      wsdlLocation = "file:/C:/Users/peter/Desktop/manageSchool/WebContent/wsdl/manageSchoolWSDL.wsdl",
                      endpointInterface = "com.gmq.psp.projects.soap.ManageSchoolWSDL")

public class ManageSchoolWSDLSOAPImpl implements ManageSchoolWSDL {

    private static final Logger LOG = Logger.getLogger(ManageSchoolWSDLSOAPImpl.class.getName());

    /* (non-Javadoc)
     * @see com.gmq.psp.projects.soap.ManageSchoolWSDL#registerSubject(com.gmq.psp.projects.soap.SubjectRequest sentSubject)*
     */
    public com.gmq.psp.projects.soap.SubjectResponse registerSubject(SubjectRequest sentSubject) {
        LOG.info("Executing operation registerSubject");
        System.out.println(sentSubject);
        try {
            com.gmq.psp.projects.soap.SubjectResponse _return = new com.gmq.psp.projects.soap.SubjectResponse();
            _return.setConfirmation("Confirmation1999039116");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.gmq.psp.projects.soap.ManageSchoolWSDL#registerStudent(com.gmq.psp.projects.soap.StudentRequest sentStudent)*
     */
    public com.gmq.psp.projects.soap.StudentResponse registerStudent(StudentRequest sentStudent) {
        LOG.info("Executing operation registerStudent");
        System.out.println(sentStudent);
        try {
            com.gmq.psp.projects.soap.StudentResponse _return = new com.gmq.psp.projects.soap.StudentResponse();
            _return.setConfirmation("Confirmation-1677567681");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.gmq.psp.projects.soap.ManageSchoolWSDL#startAssessment(com.gmq.psp.projects.soap.AssessmentRequest sentAssessment)*
     */
    public com.gmq.psp.projects.soap.AssessmentResponse startAssessment(AssessmentRequest sentAssessment) {
        LOG.info("Executing operation startAssessment");
        System.out.println(sentAssessment);
        try {
            com.gmq.psp.projects.soap.AssessmentResponse _return = new com.gmq.psp.projects.soap.AssessmentResponse();
            _return.setConfirmation("Confirmation2107139098");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
